[package]
name = "arpchat-rs"
version = "0.1.0"
authors = ["Alex Kovalov <alexkovalevkpi@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
crossbeam = "0.8.4"
cursive = "0.21.1"
gethostname = "0.5.0"
pnet = "0.35.0"
thiserror = "1.0.63"
